<?php
/**
 * Vinny's Ristorante - Legacy Reservation Handler
 * Provides basic Email & SMS alerting without API dependencies.
 */

if ($_SERVER["REQUEST_METHOD"] == "POST") {

    // 1. Collect and Sanitize Data
    $name = strip_tags(trim($_POST["customer_name"]));
    $phone = strip_tags(trim($_POST["customer_phone"]));
    $guests = isset($_POST["guest_count"]) ? $_POST["guest_count"] : "Not specified";
    $date = $_POST["res_date"];
    $time = $_POST["res_time"];
    $occasion = isset($_POST["occasion"]) ? $_POST["occasion"] : "Standard Dining";
    $special_requests = strip_tags(trim($_POST["special_requests"]));

    // 2. Set Up Recipient (Owner's Email)
    // Update this to Carmen's actual email
    $to_email = "carmen@vinnysristorante.com"; 
    $subject = "WEB RESERVATION: $name - $date @ $time";

    // 3. Construct Email Body
    $email_content = "New website reservation request:\n\n";
    $email_content .= "Customer: $name\n";
    $email_content .= "Phone: $phone\n";
    $email_content .= "Date: $date\n";
    $email_content .= "Time: $time\n";
    $email_content .= "Guests: $guests\n";
    $email_content .= "Occasion: $occasion\n";
    $email_content .= "Requests: $special_requests\n\n";
    $email_content .= "--- Automatically generated by Lenoper Infrastructure ---";

    // 4. Construct Headers
    $headers = "From: reservations@vinnysatnights.com\r\n";
    $headers .= "Reply-To: $phone\r\n";
    $headers .= "X-Mailer: PHP/" . phpversion();

    // 5. Send Email
    $success = mail($to_email, $subject, $email_content, $headers);

    // 6. Send SMS Notification (Carrier Gateway)
    // NOTE: This only works if the server has a properly configured mail transfer agent (MTA)
    $owner_phone = "6175551234"; // Update to her cell
    $carrier_domain = "@vtext.com"; // Verizon example
    $sms_message = "Vinny's: $name ($guests) on $date at $time. Ph: $phone";
    mail($owner_phone . $carrier_domain, "", $sms_message, "From: notifications@vinnysatnights.com");

    // 7. Redirect
    if ($success) {
        header("Location: thank-you.html?status=success");
        exit;
    } else {
        echo "Server Error: Email could not be sent. Please contact your administrator.";
    }

} else {
    header("Location: index.html");
    exit;
}
?>